/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/files/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Available Analysis Files
         * @description Retrieves a list of completed analysis filenames.
         *
         *     Scans the configured output directory for files ending with the analysis suffix.
         *     Returns an empty list if the directory doesn't exist or no files are found.
         *     Raises HTTPException 500 on internal server errors during listing.
         */
        get: operations["list_analysis_files_files__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis File Content
         * @description Retrieves the content of a specific analysis file.
         *
         *     Reads the specified .jsonl file from the output directory, parses each line
         *     as JSON, and returns the results. Malformed JSON lines are skipped and logged.
         *
         *     Args:
         *         filename (str): The name of the analysis file (e.g., "interview1_analysis.jsonl").
         *
         *     Returns:
         *         FileContentResponse: The content of the file including filename and results.
         *
         *     Raises:
         *         HTTPException(404): If the specified file does not exist.
         *         HTTPException(500): If there's an OS error reading the file or another internal error.
         */
        get: operations["get_analysis_file_content_files__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{filename}/sentences/{sentence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Specific Sentence Analysis
         * @description Retrieves the analysis result for a specific sentence within a file.
         *
         *     Reads the specified .jsonl analysis file line by line, searching for the
         *     entry matching the given `sentence_id`. Skips malformed lines.
         *
         *     Args:
         *         filename (str): The name of the analysis file.
         *         sentence_id (int): The ID of the sentence to retrieve.
         *
         *     Returns:
         *         AnalysisResult: The analysis data for the specified sentence.
         *
         *     Raises:
         *         HTTPException(404): If the file is not found, or the sentence_id is not found
         *                             within the file (after skipping malformed lines).
         *         HTTPException(500): If there's an OS error reading the file, a validation error
         *                             for the target sentence's data, or another internal error.
         */
        get: operations["get_specific_sentence_analysis_files__filename__sentences__sentence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Analysis Pipeline
         * @description Triggers the analysis pipeline for a specific input file to run in the background.
         *
         *     - Validates the input filename format.
         *     - Checks if the specified file exists in the configured input directory.
         *     - Schedules the `run_pipeline` function using background tasks.
         *
         *     Returns an immediate `202 Accepted` response indicating the task has been scheduled.
         *     Errors during the background task execution itself are logged but do not affect this response.
         *
         *     Args:
         *         request (AnalysisTriggerRequest): Request body containing the `input_filename`.
         *         background_tasks (BackgroundTasks): FastAPI mechanism for running background tasks.
         *
         *     Returns:
         *         AnalysisTriggerResponse: Confirmation message and the input filename.
         *
         *     Raises:
         *         HTTPException(400): If the `input_filename` has an invalid format (e.g., contains `/` or `..`).
         *         HTTPException(404): If the specified `input_filename` is not found in the input directory.
         *         HTTPException(500): If there is an unexpected internal server error during request
         *         validation or task scheduling.
         */
        post: operations["trigger_analysis_analysis__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Project
         * @description Answer a question from one project's graph, with verbatim citations.
         */
        post: operations["ask_project_ask__project_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edits/sentences/{interview_id}/{sentence_index}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit Sentence Text
         * @description Edit the text of a sentence. Generates SentenceEdited event.
         */
        post: operations["edit_sentence_edits_sentences__interview_id___sentence_index__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edits/sentences/{interview_id}/{sentence_index}/analysis/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Override Analysis Results
         * @description Override AI analysis results with human corrections. Generates AnalysisOverridden event.
         */
        post: operations["override_analysis_edits_sentences__interview_id___sentence_index__analysis_override_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edits/sentences/{interview_id}/{sentence_index}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sentence Edit History
         * @description Get complete edit history for a sentence (all events).
         */
        get: operations["get_sentence_history_edits_sentences__interview_id___sentence_index__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speakers/{interview_id}/{speaker_id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rename Speaker
         * @description Human correction: give a provisional speaker a real name.
         */
        post: operations["rename_speaker_speakers__interview_id___speaker_id__rename_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speakers/{interview_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Speakers
         * @description Human correction: two provisional handles were the same person.
         */
        post: operations["merge_speakers_speakers__interview_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speakers/{interview_id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Split Speaker
         * @description Create a new speaker and reattribute the listed fragments to them.
         *
         *     Composition of existing events (SpeakerCreated + SpeakerReattributed per
         *     fragment); no dedicated split event type. All fragments are loaded before
         *     any event is emitted, so a missing fragment aborts the whole operation.
         */
        post: operations["split_speaker_speakers__interview_id__split_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speakers/{interview_id}/fragments/{index}/reattribute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reattribute Fragment
         * @description Human correction: this fragment was said by someone else.
         */
        post: operations["reattribute_fragment_speakers__interview_id__fragments__index__reattribute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stitches/{interview_id}/{utterance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Stitch
         * @description Human correction: an identified utterance overlay was wrong; remove it.
         *
         *     `reason` is a query parameter (DELETE request bodies are stripped by some
         *     proxies/clients).
         */
        delete: operations["remove_stitch_stitches__interview_id___utterance_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{interview_id}/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Segments
         * @description Topic segments with their fragment ranges, in transcript order.
         */
        get: operations["list_segments_interviews__interview_id__segments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/segments/{interview_id}/{segment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Segment
         * @description Human correction: a segment was wrong; remove it (redraw = remove + re-run).
         *
         *     `reason` is a query parameter (DELETE request bodies are stripped by some
         *     proxies/clients).
         */
        delete: operations["remove_segment_segments__interview_id___segment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resolution/{project_id}/entities/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge Entities */
        post: operations["merge_entities_resolution__project_id__entities_merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resolution/{project_id}/entities/{canonical_id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Split Entity */
        post: operations["split_entity_resolution__project_id__entities__canonical_id__split_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resolution/{project_id}/entities/{canonical_id}/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Alias
         * @description Human correction: attach a surface to a canonical (works on locked ones).
         */
        post: operations["add_alias_resolution__project_id__entities__canonical_id__aliases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resolution/{project_id}/persons/{person_id}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Speaker */
        post: operations["link_speaker_resolution__project_id__persons__person_id__link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resolution/{project_id}/persons/{person_id}/unlink": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlink Speaker */
        post: operations["unlink_speaker_resolution__project_id__persons__person_id__unlink_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lenses/{interview_id}/items/{item_id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Override Lens Item
         * @description Human correction: fix a lens item's fields and lock it against re-runs.
         */
        post: operations["override_lens_item_lenses__interview_id__items__item_id__override_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{interview_id}/{lens_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Bundle
         * @description Export the interview x lens as an OKF bundle and return it zipped.
         */
        get: operations["download_bundle_exports__interview_id___lens_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{interview_id}/lenses/{lens}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lens Items */
        get: operations["lens_items_interviews__interview_id__lenses__lens__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/worklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Worklist */
        get: operations["review_worklist_review_worklist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speakers/rollup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Speakers Rollup */
        get: operations["speakers_rollup_speakers_rollup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_ui_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/projects/{project_id}/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Interviews */
        get: operations["list_interviews_ui_projects__project_id__interviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/interviews/{interview_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcript */
        get: operations["get_transcript_ui_interviews__interview_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/projects/{project_id}/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Personas */
        get: operations["list_personas_ui_projects__project_id__personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/personas/{project_id}/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Persona */
        get: operations["get_persona_ui_personas__project_id___person_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/projects/{project_id}/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Persons */
        get: operations["list_persons_ui_projects__project_id__persons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/persons/{project_id}/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Person */
        get: operations["get_person_ui_persons__project_id___person_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/projects/{project_id}/person-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Derive Person Id
         * @description Compute-only id derivation for the create-new-person flow — the
         *     frontend must never derive ids itself (loose-coupling requirement).
         */
        get: operations["derive_person_id_ui_projects__project_id__person_id_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Root
         * @description Basic health check endpoint.
         */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AliasRequest */
        AliasRequest: {
            /** Surface */
            surface: string;
        };
        /**
         * AnalysisResult
         * @description Represents the analysis result for a single sentence.
         */
        AnalysisResult: {
            /**
             * Sentence Id
             * @description Unique identifier for the sentence within the file.
             */
            sentence_id: number;
            /**
             * Sequence Order
             * @description Original sequence order of the sentence.
             */
            sequence_order: number;
            /**
             * Sentence
             * @description The original sentence text.
             */
            sentence: string;
            /** Function Type */
            function_type?: string | null;
            /** Structure Type */
            structure_type?: string | null;
            /** Purpose */
            purpose?: string | null;
            /** Topic Level 1 */
            topic_level_1?: string | null;
            /** Topic Level 3 */
            topic_level_3?: string | null;
            /** Overall Keywords */
            overall_keywords?: string[] | null;
            /** Domain Keywords */
            domain_keywords?: string[] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * AnalysisTriggerRequest
         * @description Request model for triggering analysis on a specific input file.
         */
        AnalysisTriggerRequest: {
            /**
             * Input Filename
             * @description Name of the input file (e.g., 'interview1.txt') located in the configured input directory.
             */
            input_filename: string;
        };
        /**
         * AnalysisTriggerResponse
         * @description Response model after successfully triggering an analysis task.
         */
        AnalysisTriggerResponse: {
            /**
             * Message
             * @description Status message indicating analysis started.
             */
            message: string;
            /**
             * Input Filename
             * @description The input filename for which analysis was triggered.
             */
            input_filename: string;
            /**
             * Task Id
             * @description Unique identifier assigned to this analysis task.
             */
            task_id: string;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /**
             * Top K
             * @default 12
             */
            top_k: number;
        };
        /**
         * EditResponse
         * @description Response model for edit operations.
         */
        EditResponse: {
            /**
             * Status
             * @description Operation status (accepted, error)
             */
            status: string;
            /**
             * Sentence Id
             * @description Sentence UUID
             */
            sentence_id: string;
            /**
             * Version
             * @description New version number after edit
             */
            version: number;
            /**
             * Event Count
             * @description Number of events generated
             */
            event_count: number;
            /**
             * Message
             * @description Human-readable message
             */
            message: string;
        };
        /**
         * EditSentenceRequest
         * @description Request model for editing sentence text.
         */
        EditSentenceRequest: {
            /**
             * Text
             * @description New sentence text
             */
            text: string;
            /**
             * Editor Type
             * @description Type of editor making the change
             * @default human
             */
            editor_type: string;
            /**
             * Note
             * @description Optional edit note/reason
             */
            note?: string | null;
        };
        /**
         * FileContentResponse
         * @description Response model for returning the content of an analysis file.
         */
        FileContentResponse: {
            /**
             * Filename
             * @description The name of the analysis file.
             */
            filename: string;
            /**
             * Results
             * @description List of analysis results for each sentence.
             */
            results: components["schemas"]["AnalysisResult"][];
        };
        /**
         * FileListResponse
         * @description Response model for listing available analysis filenames.
         */
        FileListResponse: {
            /**
             * Filenames
             * @description List of filenames for completed analyses.
             */
            filenames: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LinkRequest */
        LinkRequest: {
            /** Interview Id */
            interview_id: string;
            /** Speaker Id */
            speaker_id: string;
            /** Display Name */
            display_name?: string | null;
        };
        /** MergeRequest */
        MergeRequest: {
            /** Surviving Canonical Id */
            surviving_canonical_id: string;
            /** Merged Canonical Id */
            merged_canonical_id: string;
        };
        /** MergeSpeakersRequest */
        MergeSpeakersRequest: {
            /** Surviving Speaker Id */
            surviving_speaker_id: string;
            /** Merged Speaker Id */
            merged_speaker_id: string;
        };
        /**
         * OverrideAnalysisRequest
         * @description Request model for overriding analysis results.
         */
        OverrideAnalysisRequest: {
            /**
             * Function Type
             * @description Override function type
             */
            function_type?: string | null;
            /**
             * Structure Type
             * @description Override structure type
             */
            structure_type?: string | null;
            /**
             * Purpose
             * @description Override purpose
             */
            purpose?: string | null;
            /**
             * Keywords
             * @description Override keywords
             */
            keywords?: string[] | null;
            /**
             * Topics
             * @description Override topics
             */
            topics?: string[] | null;
            /**
             * Domain Keywords
             * @description Override domain keywords
             */
            domain_keywords?: string[] | null;
            /**
             * Note
             * @description Optional override note/reason
             */
            note?: string | null;
        };
        /** OverrideLensItemRequest */
        OverrideLensItemRequest: {
            /** Fields Overridden */
            fields_overridden: {
                [key: string]: unknown;
            };
            /** Note */
            note?: string | null;
        };
        /** ReattributeRequest */
        ReattributeRequest: {
            /** New Speaker Id */
            new_speaker_id: string;
        };
        /** RenameSpeakerRequest */
        RenameSpeakerRequest: {
            /** New Display Name */
            new_display_name: string;
        };
        /** SplitRequest */
        SplitRequest: {
            /** Surfaces */
            surfaces: string[];
            /** New Name */
            new_name: string;
        };
        /** SplitSpeakerRequest */
        SplitSpeakerRequest: {
            /** New Handle */
            new_handle: string;
            /** New Display Name */
            new_display_name: string;
            /** Fragment Indices */
            fragment_indices: number[];
        };
        /** UnlinkRequest */
        UnlinkRequest: {
            /** Interview Id */
            interview_id: string;
            /** Speaker Id */
            speaker_id: string;
            /** Note */
            note?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_analysis_files_files__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListResponse"];
                };
            };
        };
    };
    get_analysis_file_content_files__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_specific_sentence_analysis_files__filename__sentences__sentence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
                sentence_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_analysis_analysis__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisTriggerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisTriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_project_ask__project_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_sentence_edits_sentences__interview_id___sentence_index__edit_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-ID"?: string | null;
                "X-Correlation-ID"?: string | null;
            };
            path: {
                interview_id: string;
                sentence_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditSentenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    override_analysis_edits_sentences__interview_id___sentence_index__analysis_override_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-ID"?: string | null;
                "X-Correlation-ID"?: string | null;
            };
            path: {
                interview_id: string;
                sentence_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sentence_history_edits_sentences__interview_id___sentence_index__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interview_id: string;
                sentence_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_speaker_speakers__interview_id___speaker_id__rename_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-ID"?: string | null;
            };
            path: {
                interview_id: string;
                speaker_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameSpeakerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_speakers_speakers__interview_id__merge_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-ID"?: string | null;
            };
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeSpeakersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    split_speaker_speakers__interview_id__split_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-ID"?: string | null;
            };
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitSpeakerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reattribute_fragment_speakers__interview_id__fragments__index__reattribute_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-ID"?: string | null;
            };
            path: {
                interview_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReattributeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_stitch_stitches__interview_id___utterance_id__delete: {
        parameters: {
            query?: {
                reason?: string | null;
            };
            header?: {
                "X-User-ID"?: string | null;
            };
            path: {
                interview_id: string;
                utterance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_segments_interviews__interview_id__segments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_segment_segments__interview_id___segment_id__delete: {
        parameters: {
            query?: {
                reason?: string | null;
            };
            header?: {
                "X-User-ID"?: string | null;
            };
            path: {
                interview_id: string;
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_entities_resolution__project_id__entities_merge_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-ID"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    split_entity_resolution__project_id__entities__canonical_id__split_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-ID"?: string | null;
            };
            path: {
                project_id: string;
                canonical_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_alias_resolution__project_id__entities__canonical_id__aliases_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-ID"?: string | null;
            };
            path: {
                project_id: string;
                canonical_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AliasRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_speaker_resolution__project_id__persons__person_id__link_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-ID"?: string | null;
            };
            path: {
                project_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlink_speaker_resolution__project_id__persons__person_id__unlink_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-ID"?: string | null;
            };
            path: {
                project_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnlinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    override_lens_item_lenses__interview_id__items__item_id__override_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-ID"?: string | null;
            };
            path: {
                interview_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideLensItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_bundle_exports__interview_id___lens_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interview_id: string;
                lens_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lens_items_interviews__interview_id__lenses__lens__items_get: {
        parameters: {
            query?: {
                node_type?: string | null;
                min_confidence?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                interview_id: string;
                lens: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_worklist_review_worklist_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                threshold?: number;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    speakers_rollup_speakers_rollup_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                name?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_ui_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_interviews_ui_projects__project_id__interviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_ui_interviews__interview_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_personas_ui_projects__project_id__personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_persona_ui_personas__project_id___person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_persons_ui_projects__project_id__persons_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_person_ui_persons__project_id___person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    derive_person_id_ui_projects__project_id__person_id_get: {
        parameters: {
            query: {
                display_name: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
